### ISSUE TITLE
x64?

### ISSUE THREAD

**Issue by richorama** [matthiasg/zeromq-node-windows#3]
This is a great project, as I just can't get the zeromq binding to build for node.

Any chance you could compile for x64 as well?

**Comment by vpaulino** [comment]
Hi there ! 
I see that there as been 2 months since the last request to compile for x64! Is there any progress on this, or it will be not supported ? 

Thanks for your constribution and

Best regards

**Comment by matthiasg** [comment]
Well this issue has long since been rendered unnecessary I am sure. Very sad that I overlooked this issue though, Would not have been a big deal.
